export const LOCAL_STORAGE_KEY_SERVER = "FIN_THE_PEN_SERVER";
export const LOCAL_STORAGE_KEY_USERS = "FIN_THE_PEN_USERS";
export const SESSION_STORAGE_KEY_TOKEN = "FIN_THE_PEN_TOKEN";
export const LOCAL_STORAGE_KEY_SCHEDULES = "FIN_THE_PEN_SCHEDULES";
